/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef BACKGROUND
#define BACKGROUND

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class Background : public RooAbsPdf {
public:
  Background() {} ; 
  Background(const char *name, const char *title,
          RooAbsReal& _m,
          RooAbsReal& _b,
          RooAbsReal& _c);
  Background(const Background& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new Background(*this,newname); }
  inline virtual ~Background() { }

protected:
  RooRealProxy m;
  RooRealProxy b;
  RooRealProxy c;
  Double_t evaluate() const ;

private:

  ClassDef(Background,1) // Your description goes here...
};
 
#endif
