/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "Background.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(Background) 

 Background::Background(const char *name, const char *title, 
                        RooAbsReal& _m,
                        RooAbsReal& _b,
                        RooAbsReal& _c):
   RooAbsPdf(name,title), 
   m("m","m",this,_m),
   b("b","b",this,_b),
   c("c","c",this,_c)
 { 
 } 


 Background::Background(const Background& other, const char* name) :  
   RooAbsPdf(other,name), 
   m("m",this,other.m),
   b("b",this,other.b),
   c("c",this,other.c)
 { 
 } 



 Double_t Background::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
  Double_t m_D0 = 1864.84;
  Double_t m_pi = 139.57;
  Double_t dm = m - (m_D0+m_pi);
  if (dm <=0)
  {
    return 0;
  }
  return TMath::Power(dm, b)*exp(-c*dm);
 } 



