/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef FAGE
#define FAGE

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class fage : public RooAbsPdf {
public:
  fage() {} ; 
  fage(const char *name, const char *title,
          RooAbsReal& _m,
          RooAbsReal& _mu,
          RooAbsReal& _sigma,
          RooAbsReal& _epsilon,
          RooAbsReal& _rhol,
          RooAbsReal& _rhor);
  fage(const fage& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new fage(*this,newname); }
  inline virtual ~fage() { }

protected:
  RooRealProxy m;
  RooRealProxy mu;
  RooRealProxy sigma;
  RooRealProxy epsilon;
  RooRealProxy rhol;
  RooRealProxy rhor;
  Double_t evaluate() const ;

private:

  ClassDef(fage,1) // Your description goes here...
};
 
#endif
