/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef JOHNSON
#define JOHNSON

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class Johnson : public RooAbsPdf {
public:
  Johnson() {} ; 
  Johnson(const char *name, const char *title,
          RooAbsReal& _m,
          RooAbsReal& _mu,
          RooAbsReal& _sigma,
          RooAbsReal& _delta,
          RooAbsReal& _gamma);
  Johnson(const Johnson& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new Johnson(*this,newname); }
  inline virtual ~Johnson() { }

protected:
  RooRealProxy m;
  RooRealProxy mu;
  RooRealProxy sigma;
  RooRealProxy delta;
  RooRealProxy gamma;
  Double_t evaluate() const ;

private:

  ClassDef(Johnson,1) // Your description goes here...
};
 
#endif
